
// /*global systemDictionary:true */
'use strict';
//eslint-disable-next-line
systemDictionary = {
  'viessmannapi adapter settings': {
    en: 'Adapter settings for viessmannapi',
    de: 'Adaptereinstellungen für viessmannapi',
    ru: 'Настройки адаптера для viessmannapi',
    pt: 'Configurações do adaptador para viessmannapi',
    nl: 'Adapterinstellingen voor viessmannapi',
    fr: "Paramètres d'adaptateur pour viessmannapi",
    it: "Impostazioni dell'adattatore per viessmannapi",
    es: 'Ajustes del adaptador para viessmannapi',
    pl: 'Ustawienia adaptera dla viessmannapi',
    'zh-cn': 'viessmannapi2的适配器设置',
  },
  'Update device status (in minutes).': {
    en: 'Update device status (in minutes).',
    de: 'Gerätestatus aktualisieren (in Minuten).',
    ru: 'Обновить статус устройства (в минутах).',
    pt: 'Atualize o status do dispositivo (em minutos).',
    nl: 'Apparaatstatus bijwerken (in minuten).',
    fr: "Mettre à jour l'état de l'appareil (en minutes).",
    it: 'Aggiorna lo stato del dispositivo (in minuti).',
    es: 'Actualice el estado del dispositivo (en minutos).',
    pl: 'Zaktualizuj stan urządzenia (w minutach).',
    'zh-cn': '更新设备状态（以分钟为单位）。',
  },
  'Update gateway events (in minutes).': {
    en: 'Update gateway events (in minutes).',
    de: 'Gateway-Ereignisse aktualisieren (in Minuten).',
    ru: 'Обновить события шлюза (в минутах).',
    pt: 'Atualizar eventos de gateway (em minutos).',
    nl: 'Gatewaygebeurtenissen bijwerken (in minuten).',
    fr: 'Mettre à jour les événements de passerelle (en minutes).',
    it: 'Aggiorna gli eventi del gateway (in minuti).',
    es: 'Actualice los eventos de la puerta de enlace (en minutos).',
    pl: 'Zaktualizuj zdarzenia bramy (w minutach).',
    'zh-cn': '更新网关事件（以分钟为单位）。',
  },
  'Viessmannapi Password': {
    en: 'Viessmannapi Password',
    de: 'Viessmannapi Passwort',
    ru: 'Пароль Viessmannapi',
    pt: 'Senha Viessmannapi',
    nl: 'Viessmannapi-wachtwoord',
    fr: 'Mot de passe Viessmannapi',
    it: 'Password Viessmannap',
    es: 'Contraseña de Viessmannapi',
    pl: 'Hasło Viessmannapi',
    'zh-cn': 'Viessmannapi 密码',
  },
  'Viessmannapi Client ID': {
    en: 'Viessmannapi Client ID',
    de: 'Viessmannapi Client ID',
    ru: 'Viessmannapi Client ID',
    pt: 'ID do cliente Viessmannapi',
    nl: 'Viessmannapi Client ID',
    fr: 'Identifiant client Viessmannapi',
    it: 'ID client Viessmannapi',
    es: 'ID de cliente de Viessmannapi',
    pl: 'Identyfikator klienta Viessmannapi',
    'zh-cn': 'Viessmannapi 客户端 ID',
  },
  'Viessmannapi Username': {
    en: 'Viessmannapi Username',
    de: 'Viessmannapi Benutzername',
    ru: 'Имя пользователя Viessmannapi',
    pt: 'Nome de usuário Viessmannapi',
    nl: 'Viessmannapi-gebruikersnaam',
    fr: "Nom d'utilisateur Viessmannapi",
    it: 'Nome utente Viessmannapi',
    es: 'Nombre de usuario de Viessmannapi',
    pl: 'Nazwa użytkownika Viessmannapi',
    'zh-cn': 'Viessmannapi 用户名',
  },
  'Feature filter (comma-separated). Use * as wildcard. Example: heating.boiler.*,heating.burner.*': {
    en: 'Feature filter (comma-separated). Use * as wildcard. Example: heating.boiler.*,heating.burner.*',
    de: 'Funktionsfilter (kommagetrennt). Verwenden Sie * als Platzhalter. Beispiel: heating.boiler.*,heating.burner.*',
    ru: 'Фильтр функций (через запятую). Используйте * как подстановочный знак. Пример: heating.boiler.*,heating.burner.*',
    pt: 'Filtro de recursos (separado por vírgula). Use * como curinga. Exemplo: heating.boiler.*,heating.burner.*',
    nl: 'Functiefilter (komma-gescheiden). Gebruik * als jokerteken. Voorbeeld: heating.boiler.*,heating.burner.*',
    fr: 'Filtre de fonctionnalités (séparées par des virgules). Utilisez * comme caractère générique. Exemple : heating.boiler.*,heating.burner.*',
    it: 'Filtro funzionalità (separate da virgola). Usa * come carattere jolly. Esempio: heating.boiler.*,heating.burner.*',
    es: 'Filtro de funciones (separadas por comas). Use * como comodín. Ejemplo: heating.boiler.*,heating.burner.*',
    pl: 'Filtr funkcji (oddzielonych przecinkami). Użyj * jako symbolu wieloznacznego. Przykład: heating.boiler.*,heating.burner.*',
    'zh-cn': '功能过滤器（以逗号分隔）。使用 * 作为通配符。示例：heating.boiler.*,heating.burner.*',
  },
  'Allow update of virtual devices like Room Controls Devices.': {
    en: 'Allow update of virtual devices like Room Controls Devices.',
    de: 'Aktualisierung virtueller Geräte wie Einzelraumsteuerungen erlauben.',
    ru: 'Разрешить обновление виртуальных устройств, таких как устройства управления комнатой.',
    pt: 'Permitir atualização de dispositivos virtuais, como dispositivos de controle de ambiente.',
    nl: 'Update van virtuele apparaten zoals kamerregelaars toestaan.',
    fr: 'Autoriser la mise à jour des appareils virtuels tels que les commandes de pièce.',
    it: 'Consenti aggiornamento di dispositivi virtuali come i comandi ambiente.',
    es: 'Permitir actualización de dispositivos virtuales como los controles de habitación.',
    pl: 'Zezwalaj na aktualizację urządzeń wirtualnych, takich jak sterowniki pomieszczeń.',
    'zh-cn': '允许更新虚拟设备，例如房间控制设备。',
  },
  'Index of which gateway shall be used.': {
    en: 'Index of which gateway shall be used.',
    de: 'Index des zu verwendenden Gateways.',
    ru: 'Индекс используемого шлюза.',
    pt: 'Índice de qual gateway será usado.',
    nl: 'Index van de te gebruiken gateway.',
    fr: 'Index de la passerelle à utiliser.',
    it: 'Indice del gateway da utilizzare.',
    es: 'Índice de la puerta de enlace a utilizar.',
    pl: 'Indeks bramy, która ma być używana.',
    'zh-cn': '要使用的网关的索引。',
  },
  'Allowlist of IDs which allow to update to prevent rate limit with ViCare Einzelraumsteuerung. Example: 0, HeatDemandControl':
    {
      en: 'Allowlist of IDs which allow to update to prevent rate limit with ViCare Einzelraumsteuerung. Example: 0, HeatDemandControl',
      de: 'Erlaubnisliste der IDs, die zu aktualisieren sind, um Ratenlimit mit ViCare Einzelraumsteuerung zu verhindern. Beispiel: 0, HeatDemandControl',
      ru: 'Список разрешений, которые позволяют обновлять, чтобы предотвратить лимит скорости с ViCare Einzelraumsteuerung. Пример: 0, HeatDemandControl',
      pt: 'Lista de IDs que permitem atualizar para evitar o limite de taxa com ViCare Einzelraumsteuerung. Exemplo: 0, HeatDemandControl',
      nl: "Toestaanlijst van ID's die bijgewerkt mogen worden om de rate limit bij ViCare Einzelraumsteuerung te voorkomen. Voorbeeld: 0, HeatDemandControl",
      fr: 'Liste des ID qui permettent de mettre à jour pour prévenir la limite de taux avec ViCare Einzelraumsteuerung. Exemple: 0, HeatDemandControl',
      it: 'Consentire lista di ID che permettono di aggiornare per prevenire il limite di tasso con ViCare Einzelraumsteuerung. Esempio: 0, HeatDemandControl',
      es: 'Permiso de identificaciones que permiten actualizar para evitar límite de tarifas con ViCare Einzelraumsteuerung. Ejemplo: 0, HeatDemandControl',
      pl: 'Lista dozwolonych identyfikatorów, które można aktualizować, aby zapobiec limitowi szybkości w ViCare Einzelraumsteuerung. Przykład: 0, HeatDemandControl',
      'zh-cn': '允许更新的 ID 白名单，用于避免 ViCare 单房间控制的速率限制。示例: 0, HeatDemandControl',
    },
};
